runtime: python37

env_variables:
    CLOUD_SQL_USERNAME: dompm
    CLOUD_SQL_PASSWORD: userstudy_master
    CLOUD_SQL_DATABASE_NAME: userstudy_results
    CLOUD_SQL_CONNECTION_NAME: userstudy-distortion:northamerica-northeast1:userstudy-distortion-results